import os
import requests
from django.core.files.storage import default_storage
from instagrapi import Client
from django.core.exceptions import ValidationError
from instagrapi.exceptions import ClientError, TwoFactorRequired
from tempfile import NamedTemporaryFile
from instagram.models import InstagramUser,Publication

class InstagramService:
    def __init__(self):
        self.client = Client()
    def authenticate(self, username, password, otp=None):
        try:
            existing_user = InstagramUser.objects.filter(username=username, password=password).first()
            if existing_user:
                print("üîë Connexion avec un utilisateur existant...")
                return 2  
            
            print("üîë Connexion √† Instagram...")
            if otp:
                print("√âtape : Connexion avec OTP")
                login_response = self.client.login(username, password, verification_code=otp)
                if not login_response:
                    raise ValueError("√âchec de la connexion avec le code OTP")
            else:
                print("√âtape : Connexion normale")
                self.client.login(username, password)
                

            user_info = self.client.account_info()
            
            InstagramUser.objects.update_or_create(
            username=user_info.username,
            defaults={
                "password": password,
                "name": user_info.full_name,
                "profile_picture": str(user_info.profile_pic_url),
                "bio": user_info.biography,
                "bio_link": str(user_info.external_url) if user_info.external_url else None,
                "is_master": False,
            }
        )

            print(f"Informations de l'utilisateur r√©cup√©r√©es avec succ√®s : {user_info}")
            return 1

        except TwoFactorRequired:
            print("Erreur : Code OTP requis ou incorrect.")
            return 0
        except ClientError:
            print("Erreur : Nom d'utilisateur ou mot de passe incorrect.")
            return 0
        except Exception as e:
            print(f"Erreur g√©n√©rale : {e}")
            return 0

    def update_account(self, instagram_user):
        name_updated = False  
        profile_picture_updated = False  
        messageError = ""
        try:
            if instagram_user.is_master:
                print("üîí L'utilisateur est marqu√© comme 'is_master'. Connexion √† Instagram d√©sactiv√©e.")
                if instagram_user.profile_picture:
                    profile_picture_path = default_storage.path(instagram_user.profile_picture.name)
                    if os.path.exists(profile_picture_path):
                        print(f"üì∏ Mise √† jour de la photo de profil depuis : {profile_picture_path}")
                        instagram_user.save()
                        profile_picture_updated = True  
                        print("‚úÖ Photo de profil mise √† jour avec succ√®s pour l'utilisateur is_master.")
                    else:
                        print(f"‚ùå Le fichier local '{profile_picture_path}' est introuvable.")
                        raise ValidationError("‚ùå Impossible de trouver la photo de profil pour l'utilisateur is_master.")
                else:
                    print("‚ö†Ô∏è Aucune photo de profil √† mettre √† jour pour l'utilisateur is_master.")
                
                return {
                    "name_updated": name_updated,
                    "profile_picture_updated": profile_picture_updated,
                    "error_message": messageError
                }

            print("üîë Connexion √† Instagram...")

            profile_picture_path = None
            if instagram_user.profile_picture:
                profile_picture = instagram_user.profile_picture.name

                if profile_picture.startswith('http://') or profile_picture.startswith('https://'):
                    print(f"üåê T√©l√©chargement de la photo depuis l'URL : {profile_picture}")
                    try:
                        response = requests.get(profile_picture, stream=True)
                        response.raise_for_status()
                        with NamedTemporaryFile(delete=False, suffix=".jpg") as tmp_file:
                            for chunk in response.iter_content(chunk_size=1024):
                                tmp_file.write(chunk)
                            profile_picture_path = tmp_file.name
                        print(f"‚úÖ Photo t√©l√©charg√©e temporairement : {profile_picture_path}")
                    except requests.exceptions.RequestException as e:
                        raise ValidationError(f"‚ùå Erreur lors du t√©l√©chargement de la photo : {e}")
                else:
                    profile_picture_path = default_storage.path(profile_picture)
                    if os.path.exists(profile_picture_path):
                        print(f"üì∏ Changement de la photo de profil depuis le fichier local : {profile_picture_path}")
                    else:
                        print(f"‚ùå Le fichier local '{profile_picture_path}' est introuvable.")
                        profile_picture_path = None
            self.client.login(instagram_user.username, instagram_user.password)
            try:
                print("üõ†Ô∏è Mise √† jour du nom, bio et lien...")
                self.client.account_edit(
                    full_name=instagram_user.name,
                    biography=instagram_user.bio,
                    external_url=instagram_user.bio_link
                )
                print("‚úÖ Nom, bio et lien mis √† jour avec succ√®s.")
                name_updated = True
            except Exception as e:
                if "You can't change your name right now" in str(e):
                    name_updated = False
                    print("‚ö†Ô∏è Impossible de changer le nom pour le moment en raison de restrictions de fr√©quence.")
                    messageError = "‚ö†Ô∏è Unable to change the name due to frequency restrictions."
                else:
                    raise ValidationError(f"‚ö†Ô∏è Error while updating the name: {str(e)}")

            if profile_picture_path:
                print(f"üì∏ Mise √† jour de la photo de profil depuis : {profile_picture_path}")
                result = self.client.account_change_picture(profile_picture_path)

                if result:
                    print("‚úÖ Photo de profil mise √† jour avec succ√®s.")
                    profile_picture_updated = True  
                else:
                    messageError = "‚ùå Failed to change the profile picture."
                    raise ValidationError("‚ùå Failed to change the profile picture.")
            else:
                print("‚ö†Ô∏è Aucune photo de profil √† mettre √† jour.")

            if name_updated or profile_picture_updated:
                clien_info = self.client.account_info()
                instagram_user.profile_picture = str(clien_info.profile_pic_url)
                instagram_user.save()
                print("‚úÖ Les informations du compte Instagram ont √©t√© mises √† jour dans la base de donn√©es.")
            else:
                raise ValidationError(messageError)

        except ValidationError as e:
            print(f"‚ö†Ô∏è Erreur de validation : {e}")
            raise e
        except Exception as e:
            print(f"‚ùå Erreur inattendue : {str(e)}")
            raise ValidationError(f"‚ö†Ô∏è Erreur inattendue : {e}")
        finally:
            if profile_picture_path and profile_picture_path.startswith('/tmp'):
                try:
                    os.remove(profile_picture_path)
                    print(f"üßπ Fichier temporaire supprim√© : {profile_picture_path}")
                except OSError:
                    print(f"‚ö†Ô∏è Impossible de supprimer le fichier temporaire : {profile_picture_path}")

        return {
            "name_updated": name_updated,
            "profile_picture_updated": profile_picture_updated,
            "error_message": messageError
        }

    def publish_post(self, instagram_user, title, description, image_path):
        try:
            print("üîë Connexion √† Instagram...")
            self.client.login(instagram_user.username, instagram_user.password)
            if not os.path.exists(image_path):
                raise ValidationError("‚ùå Le fichier d'image sp√©cifi√© est introuvable.")
            media = self.client.photo_upload(image_path, title)
            print("‚úÖ Publication r√©ussie !")
            publication = Publication(
                instagram_user=instagram_user,
                title=title,
                description=description,
                image=image_path,
                date_posted=media.taken_at, 
                is_published=True
            )
            publication.save()
            return True

        except Exception as e:
            print(f"Erreur lors de la publication : {e}")
            raise ValidationError(f"‚ùå Erreur de publication : {e}")

    def sync_account(self, instagram_user):
        print(f"Synchronizing account for user: {instagram_user.username}")
        print("üîë Verification sur Instagram...")
        try:
            user_secondaire = self.client.login(instagram_user.username, instagram_user.password)
            if user_secondaire:
                print("ok")
                user_info = self.client.account_info()
                InstagramUser.objects.update_or_create(
                id=instagram_user.id,
                defaults={
                    "name": user_info.full_name,
                    "profile_picture": str(user_info.profile_pic_url),
                    "bio": user_info.biography,
                    "bio_link": str(user_info.external_url) if user_info.external_url else None,
                    "is_master": False,
                })
                return 1
            else:
                print("no ok")
                return 0 

        except Exception as e:
            print("no ok")
            print(f"Erreur: {str(e)}")
            return 0

